version: '3'
services:
  app:
    build: .
    ports:
      - "3001:3000"
    environment:
      - DB_HOST=postgres

  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: transaction_db
      POSTGRES_PASSWORD: Allan@2001
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: