version: '3'
services:
  app:
    build: .
    ports:
      - "3001:3000"
    environment:
      - DB_HOST=postgres
      - RABBITMQ_URL=amqp://rabbitmq
    depends_on:
      - postgres
      - rabbitmq

  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: transaction_db
      POSTGRES_PASSWORD: your_password
    volumes:
      - postgres-data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "15672:15672" # RabbitMQ Management UI
      - "5672:5672"   # RabbitMQ Port

volumes:
  postgres-data: